PUT http://localhost:8080/api/request/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJ0ZXN0LWNhc2UiLCJpYXQiOjE2OTUzODY0ODAsImV4cCI6MTY5NTM5MDA4MCwic3ViIjoiYWRtaW4ifQ.CiISLKSTjdV-6SXYzuQsP55F7gui96tsCjWUteGCnr4
status = "123"
comment = "123"
